version: '3.8'
services:
    ois-front:
        container_name: afmis-front
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3010:80'
        networks:
            - public-network
networks:
    public-network:
        external: true
