version: '3.8'
services:
    template-front:
        container_name: template-front
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3013:80
        networks:
            - public-network
networks:
    public-network:
        external: true
