export const MOCK_NOTIFICATIONS = [
    {
        id: '1',
        title: 'Vergi bəyannaməsi təqdim olundu',
        description: '2025-ci ilin II rübü üzrə vergi bəyannaməniz uğurla təqdim edildi.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: true,
    },
    {
        id: '2',
        title: 'Vergi ödənişi təsdiqi',
        description: 'Faktura №TX-202506 faylı üzrə vergi ödənişiniz qeydə alındı.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '3',
        title: 'Maliyyə hesabatı tələb olunur',
        description: '2024-cü il üçün maliyyə hesabatınızı təqdim edin.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '4',
        title: 'Vergi güzəşti xəbərdarlığı',
        description: 'Vergi güzəştinizin müddəti 10 günə bitir.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '5',
        title: 'Rüblük hesabat xatırlatması',
        description: 'III rüb üçün vergi hesabatınızı 30 iyun 2025-dək təqdim edin.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '6',
        title: 'Ödəniş cədvəli yeniləndi',
        description: 'Cari ilin vergi ödəniş cədvəli yenilənib, yoxlayın.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '7',
        title: 'Auditor yoxlaması',
        description: 'Sizin şirkətiniz üzrə planlı yoxlama təyin edildi.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '8',
        title: 'Qüsurlu bəyannamə',
        description: 'Göndərdiyiniz bəyannamədə çatışmazlıqlar aşkarlandı.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '9',
        title: 'Düzəliş təklifi',
        description: 'Bəyannamənizdə düzəliş edilməsi tələb olunur.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '10',
        title: 'Vergi güzəştindən imtina',
        description: 'Siz seçdiyiniz güzəşt proqramından imtina etdiniz.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '11',
        title: 'Vergitutma yeniləməsi',
        description: 'Vergi qanunvericiliyinə əlavə olunan dəyişikliklər.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '12',
        title: 'Xatırlatma: vaxtında ödəmə',
        description: 'Əvvəlki ödənişinizi hələ tam etməmisiniz.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
    {
        id: '13',
        title: 'Yeni qayda və tələblər',
        description: '2025-ci ilin iyul ayından etibarən qüvvəyə minəcək vergi tələbləri.',
        sender: 'Vergilər Xidməti',
        date: '2025-06-15T13:28:27.4130223',
        isSeen: false,
    },
];
