name: Deploy to Server
on:
push:
    branches:
     - main
jobs:
deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
         uses: actions/checkout@v2
     - name: Set up SSH
         uses: webfactory/ssh-agent@v0.5.3
         with:
            ssh-private-key: ${{ secrets.SSH_TEST_PRIVATE_KEY }}
     - name: Deploy to Server
        run: |
         ssh -o StrictHostKeyChecking=no root@65.108.38.170 << 'EOF'
            cd /home/projects/JobFront && \
            git pull origin test && \
            docker-compose down && \
            docker-compose -f ./docker-compose-deploy.yml up -d --build
         EOF
