name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Build check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm i

            - name: Build
              run: npm run build

    deploy:
        name: SSH & Deploy on Remote Server
        runs-on: ubuntu-latest
        needs: build
        if: github.event_name == 'push'
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Deploy to Server
              run: |
                  ssh -o StrictHostKeyChecking=no root@65.108.38.170 << 'EOF'
                      cd /home/projects/Template/Template-Front-New && \
                      git fetch origin main && \
                      git checkout main && \
                      git pull origin main && \
                      docker compose -f ./docker-compose.yml rm -sf template-front
                      docker compose -f ./docker-compose.yml up -d --build template-front
                  EOF
